### ISSUE TITLE
Numeros Narcisistas

### ISSUE THREAD

**Issue by Lucasutn** [maurirlz/Programacion-II#3]
Che, fíjate en tu función para números narcisistas, no estas contando la cantidad de dígitos, osea tu funcion ahora solo sirve para numeros de 3 cifras, y no para numeros de 4 o mas, lo mismo para 2 cifras, corregime si estoy equivocado

public static boolean numeroNarcissista(int a) {
        int aux = a;
        int d, acum = 0;
        while (a > 0) {
            d = a % 10;
            a = a / 10;
            acum += (d * d * d); //ACA EN ESTA PARTE SINO ESTOY EQUIVOCADO, ya que solo multiplicas 3 veces
        }
        if (acum == aux) {
            return true;
        } else {
            return false;
        }

    }

**Comment by maurirlz** [comment]
se, solo cuenta para 3 cifras mas porque no habia un techo que habian puesto, en ese caso podrias poner un contador para sacar el numero de digitos  que tiene y de ahi multiplicarias d * contador

si hubiera un techo de n digitos para el ejercicio lo podrias hacer asi solo pero como en el ejemplo daban un numero con 3 digitos, lo puse asi para hacerlo medio rapido y pasar a los ejercicios de objetos
